.PHONY: ex10 ex11 ex12 clean
CC := gcc
CFLAGS := -pthread

ex10:
	$(CC) ex10.c -o ex10  $(CFLAGS)

ex11:
	$(CC) ex11.c -o ex11  $(CFLAGS)

ex12:
	$(CC) ex12.c -o ex12  $(CFLAGS)

clean:
	rm -rf ex10 ex11 ex12